#ifndef TEXTURE_CONFIG_H
#define TEXTURE_CONFIG_H

#define TERRAIN_TEXTURES_UNIT      GL_TEXTURE3
#define TERRAIN_TEXTURES_UNIT_INDEX 3
#define HEIGHT_MAP_TEXTURE_UNIT       GL_TEXTURE4
#define HEIGHT_MAP_TEXTURE_UNIT_INDEX 4
#define NORMAL_MAP_TEXTURE_UNIT       GL_TEXTURE5
#define NORMAL_MAP_TEXTURE_UNIT_INDEX 5

#endif